'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowLeft,ArrowRight,Bell,CalendarDays,Check,ChevronRight,Copy,Download,Eye,EyeOff,Monitor,Search,Settings2,ShieldCheck,Smartphone,Star,Trophy,Tv,UserRound,WifiOff,X,Zap} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogTrigger,DialogClose} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Input} from '@/components/ui/input';
import {asset} from '../media';
import {plans,money} from '../content';
import {Activation} from '../activation';
import {channels,demoGames,defaults,parsePreferences,filterGames,favoriteOptions,progress,normalize,crestFor,type Preferences} from './model';

type InstallEvent=Event & {prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
const STORE='nexus.pwa.preferences.v1';
export default function ClientArea(){
 const [tab,setTab]=useState('games'),[query,setQuery]=useState(''),[sport,setSport]=useState('Todos'),[day,setDay]=useState(0),[favoritesOnly,setFavoritesOnly]=useState(false),[preferences,setPreferences]=useState<Preferences>(defaults),[ready,setReady]=useState(false),[storageWarning,setStorageWarning]=useState(false);
 const [favoriteDialog,setFavoriteDialog]=useState(false),[alertsDialog,setAlertsDialog]=useState(false),[installHelp,setInstallHelp]=useState(false),[installPrompt,setInstallPrompt]=useState<InstallEvent|null>(null),[installed,setInstalled]=useState(false),[installHidden,setInstallHidden]=useState(false),[offline,setOffline]=useState(false);
 const [channelQuery,setChannelQuery]=useState(''),[channelCategory,setChannelCategory]=useState('Todos'),[highlight,setHighlight]=useState(''),[revealed,setRevealed]=useState(false),[copyStatus,setCopyStatus]=useState(''),[renew,setRenew]=useState(false),[screens,setScreens]=useState(3),[nearExpiry,setNearExpiry]=useState(false);
 useEffect(()=>{try{setPreferences(parsePreferences(localStorage.getItem(STORE)))}catch{setStorageWarning(true)}setReady(true);const online=()=>setOffline(!navigator.onLine);online();addEventListener('online',online);addEventListener('offline',online);setInstalled(matchMedia('(display-mode: standalone)').matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone));const install=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallEvent)};const done=()=>{setInstalled(true);setInstallPrompt(null)};addEventListener('beforeinstallprompt',install);addEventListener('appinstalled',done);if(location.protocol==='https:'&&'serviceWorker' in navigator)navigator.serviceWorker.register('/nexus-sw.js',{scope:'/app'}).catch(()=>{});return()=>{removeEventListener('online',online);removeEventListener('offline',online);removeEventListener('beforeinstallprompt',install);removeEventListener('appinstalled',done)}},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(STORE,JSON.stringify(preferences))}catch{setStorageWarning(true)}},[preferences,ready]);
 function favorite(name:string){setPreferences(p=>({...p,favorites:p.favorites.includes(name)?p.favorites.filter(x=>x!==name):[...p.favorites,name]}))}
 function goChannel(id:string|null){if(!id)return;setHighlight(id);setChannelQuery('');setChannelCategory('Todos');setTab('guide')}
 async function install(){if(!installPrompt){setInstallHelp(true);return}try{await installPrompt.prompt();const choice=await installPrompt.userChoice;if(choice.outcome==='accepted')setInstalled(true)}catch{setInstallHelp(true)}finally{setInstallPrompt(null)}}
 async function copy(kind:string,value:string){try{await navigator.clipboard.writeText(value);setCopyStatus(kind+' copiado — dados demonstrativos.')}catch{setRevealed(true);setCopyStatus('Cópia indisponível. Selecione o texto exibido para copiar manualmente.')}}
 const games=filterGames(demoGames,query,sport,day,preferences.favorites,favoritesOnly);
 const visibleChannels=channels.filter(c=>(channelCategory==='Todos'||c.category===channelCategory)&&normalize(c.name+' '+c.now).includes(normalize(channelQuery)));
 const remaining=nearExpiry?3:248;
 return <div className="member-app"><a className="skip" href="#member-main">Pular para o conteúdo</a><Tabs value={tab} onValueChange={setTab} className="member-shell">
  <aside className="member-sidebar"><a className="member-brand" href="/"><img className="member-mark" src={asset("nexus.svg")} alt="" width="34" height="35"/><span>NEXUS<small>PLAYTV</small></span></a><span className="member-nav-label">SEU UNIVERSO</span><TabsList className="member-nav" aria-label="Área do cliente"><TabsTrigger value="games"><Trophy/><span>Jogos de hoje</span></TabsTrigger><TabsTrigger value="guide"><Tv/><span>Guia de canais</span></TabsTrigger><TabsTrigger value="account"><UserRound/><span>Minha conta</span></TabsTrigger></TabsList><div className="sidebar-bottom"><button onClick={()=>setFavoriteDialog(true)}><Star size={19}/> Meus favoritos <span>{preferences.favorites.length}</span></button><button onClick={()=>setAlertsDialog(true)}><Bell size={19}/> Preferências de alertas</button><a href="/"><ArrowLeft size={17}/> Voltar ao site</a><p>STREAMCORE™ ULTRA-P2P<br/>ENGINE GO™ · BAIXA LATÊNCIA</p></div></aside>
  <div className="member-body"><header className="member-header"><div><span className="member-mobile-brand">NEXUS <small>PLAYTV</small></span><span className="member-desktop-title">ÁREA DO CLIENTE <ChevronRight size={14}/> {tab==='games'?'Jogos de hoje':tab==='guide'?'Guia de canais':'Minha conta'}</span></div><div className="member-header-actions"><button onClick={()=>setAlertsDialog(true)} aria-label="Preferências de alertas"><Bell size={20}/></button><button className="member-avatar" onClick={()=>setTab('account')} aria-label="Abrir minha conta">N</button></div></header>
  <main id="member-main"><div className="member-demo"><ShieldCheck size={15}/><span>Modo demonstração · jogos, canais e assinatura de exemplo.</span></div>{offline&&<div className="member-offline" role="status"><WifiOff size={17}/> Sem conexão. Você está vendo exemplos; atualização e renovação precisam de internet.</div>}
  <div className="member-topline"><div><span className="member-kicker">{tab==='account'?'TUDO SOB SEU CONTROLE':'SEU PRÓXIMO PLAY COMEÇA AQUI'}</span><h1>{tab==='games'?'Hoje tem jogo.':tab==='guide'?'O que está passando?':'Minha assinatura.'}</h1></div><button className="member-link" onClick={()=>setFavoriteDialog(true)}><Star size={16}/> Seus favoritos <ChevronRight size={15}/></button></div>
  {nearExpiry&&<div className="member-renew-banner"><div><Zap size={20}/><p>Sua assinatura vence em <strong>3 dias.</strong><small>Exemplo de lembrete de renovação.</small></p></div><button onClick={()=>setRenew(true)}>Renovar no PIX <ArrowUpRight size={17}/></button></div>}
  <TabsContent value="games" className="member-tab-content"><div className="member-content-grid"><section className="member-games"><div className="member-filter-row"><div className="member-date"><CalendarDays size={17}/><button className={day===0?'selected':''} onClick={()=>setDay(0)}>Hoje <small>16 SET</small></button><button className={day===1?'selected':''} onClick={()=>setDay(1)}>Amanhã <small>17 SET</small></button></div><span className="member-timezone">Horário de Brasília · amostra</span></div><div className="member-search"><Search size={19}/><Input aria-label="Buscar time ou campeonato" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Time ou campeonato"/>{query&&<button aria-label="Limpar busca de jogos" onClick={()=>setQuery('')}><X size={17}/></button>}</div><div className="member-filters" aria-label="Filtrar jogos">{['Todos','Futebol','Basquete','Lutas'].map(s=><button key={s} aria-pressed={sport===s} onClick={()=>setSport(s)}>{s}</button>)}<button className="favorites-filter" aria-pressed={favoritesOnly} onClick={()=>setFavoritesOnly(!favoritesOnly)}><Star size={15}/> Favoritos</button></div>
  <div className="member-result-heading"><h2>{favoritesOnly?'Sua torcida em campo':'Na sua agenda'}</h2><span aria-live="polite">{games.length} {games.length===1?'evento':'eventos'}</span></div>
  {games.length===0?<div className="member-empty"><Search/><h3>Nenhum jogo por aqui.</h3><p>{favoritesOnly&&preferences.favorites.length===0?'Escolha seus times e atletas para montar sua agenda.':'Tente outro time, campeonato ou filtro.'}</p><button onClick={()=>{setQuery('');setSport('Todos');setFavoritesOnly(false)}}>Ver todos os jogos</button>{favoritesOnly&&<button onClick={()=>setFavoriteDialog(true)}>Escolher favoritos</button>}</div>:<div className="member-game-list">{games.map((g,i)=>{const channel=channels.find(c=>c.id===g.channel);const starred=g.tags.some(t=>preferences.favorites.includes(t));return <article className={'member-game '+(i===0&&day===0?'featured-game':'')} key={g.id}>{i===0&&day===0&&<img className="member-game-backdrop" src="/images/stadium.webp" alt="" width="1536" height="864"/>}<div className="member-game-meta"><span>{g.competition}</span><button onClick={()=>favorite(g.tags[0])} aria-label={(preferences.favorites.includes(g.tags[0])?'Remover ':'Favoritar ')+g.tags[0]} aria-pressed={preferences.favorites.includes(g.tags[0])}><Star size={18} fill={preferences.favorites.includes(g.tags[0])?'currentColor':'none'}/></button></div><div className="member-fixture"><div className="member-team">{crestFor(g.home)?<img className="team-crest" src={asset(crestFor(g.home)!)} alt={'Escudo do '+g.home} width="40" height="40" loading="lazy"/>:<span className="team-monogram">{g.home.slice(0,3).toUpperCase()}</span>}<strong>{g.home}</strong></div><div className="member-kickoff"><strong>{g.time}</strong><span>{g.sport==='Lutas'?'EVENTO':'×'}</span></div><div className="member-team">{crestFor(g.away)?<img className="team-crest" src={asset(crestFor(g.away)!)} alt={'Escudo do '+g.away} width="40" height="40" loading="lazy"/>:<span className="team-monogram">{g.away.split(' ').map(w=>w[0]).join('').slice(0,3).toUpperCase()}</span>}<strong>{g.away}</strong></div></div><div className="member-game-footer">{channel?<button onClick={()=>goChannel(channel.id)}><img src={asset(channel.file)} alt={channel.name} width="85" height="24"/><span>Ver canal <ChevronRight size={15}/></span></button>:<span className="member-unconfirmed">Transmissão a confirmar</span>}<span>{starred?<><Star size={12}/> Sua torcida</>:'Canal ilustrativo'}</span></div></article>})}</div>}<p className="member-small-note">Confrontos, horários e transmissões desta prévia são fictícios. A agenda real dependerá de fonte verificada e correspondência com a grade NEXUS.</p></section>
  <aside className="member-rail"><section className="member-panel favorites-panel"><Star className="panel-icon"/><span className="member-kicker">SUA TORCIDA, PRIMEIRO</span><h2>O seu time.<br/>A sua agenda.</h2><p>Escolha quem você acompanha. Encontre os jogos dos seus favoritos em um toque.</p><div className="member-favorite-chips">{preferences.favorites.slice(0,4).map(f=><span key={f}>{f}</span>)}</div><button className="member-primary" onClick={()=>setFavoriteDialog(true)}>{preferences.favorites.length?'Editar favoritos':'Escolher favoritos'} <ArrowRight size={17}/></button></section><section className="member-panel account-glance"><span className="member-kicker">SUA ASSINATURA · EXEMPLO</span><h3>Anual VIP <span>3 telas</span></h3><div className="days-meter"><strong>{remaining}</strong><span>dias restantes</span></div><button className="member-link" onClick={()=>setTab('account')}>Gerenciar assinatura <ChevronRight size={16}/></button></section></aside></div></TabsContent>
  <TabsContent value="guide" className="member-tab-content"><div className="member-guide-head"><div className="member-search"><Search size={19}/><Input aria-label="Buscar canal ou programa" value={channelQuery} onChange={e=>setChannelQuery(e.target.value)} placeholder="Canal ou programa"/></div><span>AGORA · 18:35 <small>Horário demonstrativo</small></span></div><div className="member-filters">{['Todos','Esportes','Filmes e séries'].map(c=><button key={c} aria-pressed={channelCategory===c} onClick={()=>setChannelCategory(c)}>{c}</button>)}</div><div className="member-epg">{visibleChannels.map(c=><article key={c.id} className={highlight===c.id?'highlighted':''}><div className="epg-channel"><img src={asset(c.file)} alt={c.name} width="106" height="40"/><span>Canal {c.number} · exemplo</span></div><div className="epg-now"><span>NO AR · EXEMPLO</span><h2>{c.now}</h2><div className="epg-progress" role="progressbar" aria-label={'Progresso de '+c.now} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress(c.start,c.end,1115))}><i style={{width:progress(c.start,c.end,1115)+'%'}}/></div><small>{Math.floor(c.start/60)}:{String(c.start%60).padStart(2,'0')} — {Math.floor(c.end/60)}:{String(c.end%60).padStart(2,'0')}</small></div><div className="epg-next"><span>A SEGUIR</span><p>{c.next}</p></div></article>)}</div>{!visibleChannels.length&&<div className="member-empty"><Tv/><h3>Nenhum canal encontrado.</h3><button onClick={()=>{setChannelQuery('');setChannelCategory('Todos')}}>Limpar filtros</button></div>}<p className="member-small-note">Grade demonstrativa. Sem transmissão de vídeo nesta área. A programação real será sincronizada com o EPG do serviço.</p></TabsContent>
  <TabsContent value="account" className="member-tab-content"><div className="member-account-grid"><section className="member-subscription"><div className="member-card-top"><span>NEXUS <small>PLAYTV</small></span><span><ShieldCheck size={15}/> DEMONSTRAÇÃO</span></div><span className="member-kicker">SEU PLANO</span><h2>Anual <em>VIP.</em></h2><div className="subscription-data"><div><strong>3</strong><span>telas</span></div><div><strong>{remaining}</strong><span>dias restantes</span></div><div><strong>{money(plans[3].prices[2])}</strong><span>total de 365 dias</span></div></div><div className="subscription-term"><span>Período ilustrativo</span><span>{nearExpiry?'Vence em 3 dias':'Assinatura ativa'}</span></div><button className="member-primary" onClick={()=>setRenew(true)}>Renovar via PIX <Zap size={18}/></button><button className="member-link" onClick={()=>setRenew(true)}>Alterar quantidade de telas <ChevronRight size={17}/></button></section>
  <section className="member-panel member-credentials"><div className="member-section-title"><h2>Seu acesso</h2><button aria-label={revealed?'Ocultar dados':'Mostrar dados'} onClick={()=>setRevealed(!revealed)}>{revealed?<EyeOff size={19}/>:<Eye size={19}/>}</button></div><p>Dados fictícios, sem acesso a transmissões.</p>{[['Usuário','nexus_demo'],['Senha','exemplo_sem_acesso'],['DNS','https://demo.invalid'],['Playlist M3U','https://demo.invalid/get.php?username=nexus_demo&password=exemplo_sem_acesso&type=m3u_plus']].map(([label,value])=><div className="credential-row" key={label}><div><span>{label}</span><code>{revealed?value:'••••••••••••'}</code></div><button aria-label={'Copiar '+label} onClick={()=>copy(label,value)}><Copy size={17}/></button></div>)}<p role="status" className="member-copy-status">{copyStatus}</p><a className="member-secondary" href="/cartao-vip-demonstrativo.pdf" download><Download size={17}/> Baixar dossiê de exemplo</a></section>
  <section className="member-panel member-activation"><img src={asset('vision.webp')} alt="Celular enquadrando uma Smart TV" width="1254" height="706"/><div><span className="member-kicker">NEXUS VISION AI™</span><h2>Uma nova TV.<br/>O mesmo universo.</h2><p>Veja como funciona a configuração por foto.</p><Dialog><DialogTrigger asChild><button className="member-secondary"><Smartphone size={17}/> Ativar TV por foto</button></DialogTrigger><DialogContent className="activation-modal"><DialogTitle>Ativação por foto</DialogTitle><DialogDescription>Demonstração. A leitura real e a configuração precisam do serviço Nexus Vision AI.</DialogDescription><Activation full/></DialogContent></Dialog></div></section><section className="member-panel member-account-settings"><h2>Do seu jeito.</h2><button onClick={()=>setFavoriteDialog(true)}><Star size={19}/> Times e atletas favoritos <ChevronRight size={17}/></button><button onClick={()=>setAlertsDialog(true)}><Bell size={19}/> Preferências de alertas <ChevronRight size={17}/></button><div className="demo-expiry"><label htmlFor="expiry-demo">Ver exemplo de vencimento em 3 dias</label><Switch id="expiry-demo" checked={nearExpiry} onCheckedChange={setNearExpiry}/></div><p>O vencimento acima é ilustrativo. Na conta real, será calculado pelo servidor.</p></section></div></TabsContent>
  {!installed&&!installHidden&&<div className="member-install"><span className="install-icon"><Smartphone size={23}/></span><div><strong>A NEXUS, sempre à mão.</strong><p>Adicione à tela inicial do celular.</p></div><button className="install-action" onClick={install}>Instalar <Download size={16}/></button><button className="install-close" aria-label="Dispensar convite de instalação" onClick={()=>setInstallHidden(true)}><X size={17}/></button></div>}
  </main><footer className="member-footer"><span>NEXUS PLAYTV</span><span>Seu entretenimento. Sua rotina.</span></footer></div></Tabs>
  <Dialog open={favoriteDialog} onOpenChange={setFavoriteDialog}><DialogContent className="member-dialog"><DialogTitle>Quem faz você torcer?</DialogTitle><DialogDescription>Escolha times, competições e atletas. Os favoritos ficam salvos neste aparelho.</DialogDescription><div className="favorite-options">{favoriteOptions.map(f=><button key={f} aria-pressed={preferences.favorites.includes(f)} onClick={()=>favorite(f)}><span>{f}</span>{preferences.favorites.includes(f)?<Check size={18}/>:<Star size={18}/>}</button>)}</div>{storageWarning&&<p role="status">O navegador não permitiu salvar. Suas escolhas valem apenas nesta sessão.</p>}<DialogClose asChild><button className="member-primary">Concluir <Check size={18}/></button></DialogClose></DialogContent></Dialog>
  <Dialog open={alertsDialog} onOpenChange={setAlertsDialog}><DialogContent className="member-dialog"><DialogTitle>Só o que importa para você.</DialogTitle><DialogDescription>Escolha os alertas que deseja receber quando o serviço de notificações estiver conectado.</DialogDescription>{([['gameDay','No dia do jogo','Agenda dos seus favoritos.'],['kickoff','15 minutos antes','Tempo de preparar sua TV.'],['renewal','Antes do vencimento','Lembrete para renovar o plano.']] as const).map(([key,label,description])=><div className="alert-preference" key={key}><label htmlFor={key}><strong>{label}</strong><span>{description}</span></label><Switch id={key} checked={preferences.alerts[key]} onCheckedChange={v=>setPreferences(p=>({...p,alerts:{...p.alerts,[key]:v}}))}/></div>)}<div className="push-status"><Bell size={20}/><p><strong>Notificações ainda não ativadas.</strong> Estas escolhas ficam salvas localmente. O envio depende de integração e da sua permissão no aparelho.</p></div><DialogClose asChild><button className="member-primary">Salvar preferências <Check size={18}/></button></DialogClose></DialogContent></Dialog>
  <Dialog open={installHelp} onOpenChange={setInstallHelp}><DialogContent className="member-dialog"><DialogTitle>NEXUS na sua tela inicial.</DialogTitle><DialogDescription>A instalação fica disponível no site publicado, em navegador compatível. Este arquivo de revisão não instala um app.</DialogDescription><div className="install-instructions"><h3>iPhone / iPad</h3><p>Abra o site no Safari, toque em Compartilhar e em “Adicionar à Tela de Início”.</p><h3>Android</h3><p>Abra o site no Chrome. Use “Instalar app” ou “Adicionar à tela inicial” no menu do navegador, quando disponível.</p></div></DialogContent></Dialog>
  <Dialog open={renew} onOpenChange={setRenew}><DialogContent className="member-dialog"><DialogTitle>Continue no seu universo.</DialogTitle><DialogDescription>Resumo de renovação demonstrativo. Nenhuma cobrança será criada.</DialogDescription><Tabs value={String(screens)} onValueChange={v=>setScreens(Number(v))}><TabsList aria-label="Telas da renovação">{[1,2,3].map(n=><TabsTrigger key={n} value={String(n)}>{n} {n===1?'tela':'telas'}</TabsTrigger>)}</TabsList></Tabs><div className="member-renew-summary"><span>Anual VIP · 365 dias</span><strong>{money(plans[3].prices[screens-1])}</strong><small>Total do novo período · {screens} {screens===1?'tela':'telas'}</small></div><div className="push-status"><Zap size={20}/><p>O PIX Copia e Cola e o QR Code virão da cobrança real. Seu acesso só será renovado após a confirmação do pagamento.</p></div><p className="member-small-note">Mudanças durante a vigência dependem das regras de ajuste e crédito do plano. Não há cobrança proporcional calculada nesta prévia.</p><button className="member-primary" disabled>PIX indisponível nesta demonstração</button><DialogClose asChild><button className="member-link">Voltar à minha conta</button></DialogClose></DialogContent></Dialog>
 </div>
}
