'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,ChevronLeft,ChevronRight,Pause,Play,ScanLine,Monitor,Smartphone,ShieldCheck,Copy,Download,Check,Menu,Layers,Radio,Zap,MoveUpRight,Camera,CreditCard} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {plans,money,categories,devices,faqs,contact} from './content';

function Logo(){return <span className="logo"><svg width="33" height="34" viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M4 33V8L14 4V29L4 33Z M15 5L35 28V36L25 32L15 20V5Z M26 5L36 1V25L26 14V5Z" fill="currentColor"/></svg><span>NEXUS<small>PLAYTV</small></span></span>}
function Photo({i,className='',alt,priority=false}:{i:number,className?:string,alt?:string,priority?:boolean}){return <img className={className} src={`/images/gallery-${i}.webp`} width="360" height="560" alt={alt??categories[i]} loading={priority?"eager":"lazy"} fetchPriority={priority?"high":undefined}/>}
export function Activation({full=false}:{full?:boolean}){const [step,setStep]=useState(0);return <div className={`activation-demo ${full?'full':''}`}><div className="tv"><div className="tv-top"><Logo/><span>DEMONSTRAÇÃO</span></div>{step<2?<div className="tv-connect"><ScanLine/><p>{step===0?'Vamos conectar sua TV?':'Informações identificadas'}</p><small>{step===0?'Abra o aplicativo compatível para começar.':'A configuração é preparada pelo Nexus Vision AI.'}</small><div className="pair-code">NEXUS · DEMO</div></div>:<div className="tv-ready"><Photo i={0}/><div><span>CONFIGURAÇÃO CONCLUÍDA</span><h3>Seu próximo play.</h3><p>Exemplo de interface</p></div></div>}<div className="tv-bottom">NEXUS VISION AI™ <span>{step+1} / 3</span></div></div><div className="phone"><div className="phone-notch"/><Camera size={20}/><span>Foto da tela</span><div className="camera-frame"><ScanLine size={62} strokeWidth={1}/></div><p>{['Enquadrar a TV','Reconhecer os dados','Tudo conectado'][step]}</p><span className="phone-pill">{step===2?<Check size={16}/>:<ScanLine size={16}/>} {step===2?'Pronto':'Vision AI'}</span></div><div className="demo-control"><span>Demonstração interativa</span><button className="text-link" onClick={()=>setStep((step+1)%3)}>{step===2?'Recomeçar':'Próxima etapa'} <ArrowRight size={16}/></button></div></div>}
export function VipCard(){const [copied,setCopied]=useState(false),[player,setPlayer]=useState(false),[copyError,setCopyError]=useState(false);async function copy(){try{const text='DEMONSTRAÇÃO — usuário: nexus_demo | senha: exemplo_sem_acesso | DNS: demo.invalid';if(navigator.clipboard){await navigator.clipboard.writeText(text)}else{const el=document.createElement('textarea');el.value=text;el.style.position='fixed';el.style.opacity='0';document.body.appendChild(el);el.select();const ok=document.execCommand('copy');el.remove();if(!ok)throw new Error('copy')}setCopied(true);setCopyError(false)}catch{setCopied(false);setCopyError(true)}}return <div className="vip-card"><div className="vip-head"><Logo/><span>VIP ACCESS</span></div><div className="vip-main"><small>SEU UNIVERSO, CONECTADO.</small><h3>NEXUS <em>Black.</em></h3><p>ANUAL VIP <span>01 TELA</span></p></div><div className="vip-data"><div><small>ACESSO DEMONSTRATIVO</small><strong>nexus_demo</strong></div><ShieldCheck size={27}/></div><div className="vip-actions"><Dialog open={player} onOpenChange={setPlayer}><DialogTrigger asChild><button><Play size={16}/> Abrir player</button></DialogTrigger><DialogContent><DialogTitle>Player demonstrativo</DialogTitle><DialogDescription>Exemplo visual. Nenhuma transmissão ou conta real está conectada.</DialogDescription><Photo i={0} className="player-photo"/><p>Escolha seu entretenimento no player indicado após a ativação.</p></DialogContent></Dialog><button onClick={copy}><Copy size={16}/>{copied?'Copiado':'Copiar acesso'}</button><DialogClose asChild><a href="#compatibilidade" aria-label="Como configurar"><ScanLine size={18}/></a></DialogClose></div><span className="vip-note" role="status">{copyError?'Copie manualmente: nexus_demo / exemplo_sem_acesso · demo.invalid':copied?'Dados fictícios copiados. Não permitem acesso.':'DEMONSTRAÇÃO · SEM CREDENCIAIS REAIS'}</span></div>}
