location ^~ /ops-dc63c70de21f8e65414e328e55757543de047e6e2fbcdbc6 {
    proxy_pass http://127.0.0.1:5058;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_http_version 1.1;
    proxy_buffering off;
}
